name: social-data-environment

dependencies:
  - python=2.7
  - json
  - cPickle
  - uuid
  - time
  - urllib2
  - httplib
  - numpy
  - scipy
  - sklearn
  - toolz
  - matplotlib
  - dill
  - pandas
  - bokeh
  - seaborn
  - pymongo
  - pip:
    - git+https://github.com/blaze/dask.git#egg=dask[complete]
    - git+https://github.com/sixohsix/twitter.git
